### ISSUE TITLE
Affix Firefox glitch

### ISSUE THREAD

**Issue by DennisVis** [mgcrea/angular-strap#1579]
There is a glitch in regards to using affix in Firefox. When you scroll to the bottom of a page in Firefox the class 'affix-bottom' get's toggled on the affix element rapidly. 

It seems to me this might be related to the following bootstrap issue: https://github.com/twbs/bootstrap/issues/4647

The issue can be easily reproduced on the AngularStrap site. Use Firefox and resize your browser window to about 600px height or less. Scroll all the way down, then slowly scroll up to clearly see the glitch in the left navigation.

A work-around I'm using right now is including the following in my stylesheet:

``` css
html, body {
  height: auto;
  position: relative;
}

.affix-bottom {
  bottom: 300px;
  position: absolute;
}
```
