### ISSUE TITLE
What do you think about listing multiples alerts ?

### ISSUE THREAD

**Issue by grrseguin** [mgcrea/angular-strap#1865]
Hello,

I use the Alert module for all my promises. Therefore, i have the case where several alerts popping up at the same time.

Actually, all this alerts are stacked. Is it possible to list them the one below the other ?

Thanks,

Guillaume

NB: the [angular-growl](https://github.com/marcorinck/angular-growl) module has implemented this feature.

**Comment by just-boris** [comment]
Hello, I am using alerts for the same purposes. The main idea is to put these alerts into special element using `container` option:
```js
$alert({
  title: 'Error',
  content: 'Something went wrong',
  container: angular.element('.alerts-container')
});
```
Then give `.alerts-container` following styles
```less
.alerts-container {
  // place container aside
  position: fixed;
  top: 50px;
  right: 0; 
  // here is width of alerts
  width: 300px; 
  // it allows alerts to stack and get scroll, if there would be so many alerts
  overflow: scroll;
  max-height: 100%;
  &:empty {
    // we don't need to show container if there is no alerts
    display: none;
  }
}
```
