### ISSUE TITLE
Screen flickers after modal/aside close - Chrome v49

### ISSUE THREAD

**Issue by vrpruthvi** [mgcrea/angular-strap#2065]
Screen flickers after closing modal/aside. This is happening for **Chrome v49**(not happening for previous versions). Works fine on Safari and Firefox.
To reproduce issue:
1. Open http://mgcrea.github.io/angular-strap/#/modals in Chrome v49
2. Open and close modal/aside to observe flickering

Doesn't happen on bootstrap site: http://getbootstrap.com/javascript/#modals

**Comment by mshref17** [comment]
+1

**Comment by mshref17** [comment]
Did you fix this or found a workaround for it

**Comment by ruscinc** [comment]
In actual version **2.3.7**, it's because a delay on **leave animation** in **CSS** angular-motion.css. 
What I did:

- Direct in CSS, in line 180 in `.../bower_components/angular-motion/dist/angular-motion.css`

I changed animation-delay from 0.3 to 0(zero): `animation-delay: 0.3s;` to `animation-delay: 0s;`, but instead you can delete that block.. 
```css
.modal-backdrop.am-fade.ng-leave,
.aside-backdrop.am-fade.ng-leave {
  -webkit-animation-delay: 0s;
          animation-delay: 0s;
}
```

- Direct in **LESS** source, you can change `animation-delay: @fade-duration;` to `animation-delay: 0;` or remove lines 87 to 89 in `.../bower_components/angular-motion/src/fade/fade.less`

```less
.modal-backdrop, .aside-backdrop {
  &.am-fade {
    background: rgba(0, 0, 0, .5);
    animation-duration: @fade-duration / 2;
    &.ng-leave {
      animation-delay: @fade-duration;
    }
  }
}
```

I don't know if happens only in Chrome, because I saw in FireFox too and now works fine without the delay.
Tell me if works. 

PS.: differently from bootstrap, angular-strap uses different way to display modals and their animations (angular-animate).
I think that bootstrap uses only uses fade,fade-in:
```less
// Bootstrap 3 Modal background
.modal-backdrop {
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: @zindex-modal-background;
  background-color: @modal-backdrop-bg;
  // Fade for backdrop
  &.fade { .opacity(0); }
  &.in { .opacity(@modal-backdrop-opacity); }
}
```
...
```less
.modal-backdrop.in {
    filter: alpha(opacity=50);
    opacity: 0.5;
}
.modal-backdrop.fade {
    filter: alpha(opacity=0);
    opacity: 0;
}

.fade.in {
    opacity: 1;
}
```
