### ISSUE TITLE
in angular-strap.js file at line 2214 "var dialogBaseZindex = 1050",Should be 10050

### ISSUE THREAD

**Issue by yangsong158** [mgcrea/angular-strap#2149]
because 

``` css
.modal {
    display: none;
    position: fixed;
    z-index: 10050;
    -webkit-overflow-scrolling: touch;
    outline: 0;
}
```

in bootstrap.css
Please verify tks
