### ISSUE TITLE
Unable to use animations with Tabs

### ISSUE THREAD

**Issue by n1te1337** [mgcrea/angular-strap#709]
Hi, 

I can't seem to get the `am-fade` animation to work with Tabs. 

As per example I've added the following css:

``` css
.tabs.am-fade .tab-pane {
  opacity: 1;
  transition: opacity .3s ease;
  min-height:60px;
}

.tabs.am-fade .tab-pane.active-add {
  display: block;
  opacity: 0;
}

.tabs.am-fade .tab-pane.active-add.active-add-active {
  opacity: 1;
}

.tabs.am-fade .tab-pane.active-remove {
  display: none;
}
```

but when I switch between the tabs nothing happens.

I tried to do the same with the plunker from the docs but the only way I can get it to fade is when I click on one of the radio-group buttons underneath the tabs (when I click on the normal tab buttons it doesn't fade): http://plnkr.co/edit/Yol2E7Kps0YjOmYsgq2Y?p=preview

Is this a bug, or am I doing it wrong?
